apiVersion: v1
kind: Pod
metadata:
  name: busybox
  annotations:
    kubeovn.io/subnet: subnet1
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
