apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment-2
  namespace: underlay2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox2
  template:
    metadata:
      labels:
        app: busybox2
      annotations:
        ovn.kubernetes.io/logical_switch: subnet2
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent  # 添加 imagePullPolicy
        command:
          - sleep
          - "3600"