kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: ipvs
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
  apiServerPort: 0
  podSubnet: "10.16.0.0/16"
  serviceSubnet: "10.96.0.0/12"
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
    name: config
    etcd:
      local:
        dataDir: "/root/etcd"
nodes:
  - role: control-plane
    image: kindest/node:v1.27.0
  - role: control-plane
    image: kindest/node:v1.27.0