apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "kube-ovn-worker,kube-ovn-worker2"
  type: "centralized"
  external-gw-nic: "eth0"
  external-gw-addr: "10.30.0.1/16"